// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb9E9788LJRjlsXQofgTaLnJ5kLMkBvKQ',
    appId: '1:319330223109:web:d97cfb4a49b1619f4c886c',
    messagingSenderId: '319330223109',
    projectId: 'fir-auth-example-65a30',
    authDomain: 'fir-auth-example-65a30.firebaseapp.com',
    storageBucket: 'fir-auth-example-65a30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wRzqEYJza87DqVboCIcgvtn5IefNLAs',
    appId: '1:319330223109:android:bf2588b8aafe87444c886c',
    messagingSenderId: '319330223109',
    projectId: 'fir-auth-example-65a30',
    storageBucket: 'fir-auth-example-65a30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLAWUtlg-WIfZHoVVG7zY1-24KDJzLrkk',
    appId: '1:319330223109:ios:ba1f3d77dfd0ade74c886c',
    messagingSenderId: '319330223109',
    projectId: 'fir-auth-example-65a30',
    storageBucket: 'fir-auth-example-65a30.appspot.com',
    iosClientId: '319330223109-asv4euc9ltrpbacq1hnl47pnunfkov2u.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebaseUiExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLAWUtlg-WIfZHoVVG7zY1-24KDJzLrkk',
    appId: '1:319330223109:ios:ba1f3d77dfd0ade74c886c',
    messagingSenderId: '319330223109',
    projectId: 'fir-auth-example-65a30',
    storageBucket: 'fir-auth-example-65a30.appspot.com',
    iosClientId: '319330223109-asv4euc9ltrpbacq1hnl47pnunfkov2u.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebaseUiExample',
  );
}
